### ISSUE TITLE
Bug in OrderTypeConverter

### ISSUE THREAD

**Issue by dimsumcode** [ridicoulous/LiquidQuoine.Net#16]
Getting error on PlaceMarginOrder() "order type not valid"
Looking at the source of OrderTypeConverter.c, this looks like a bad search/replace bug:

`new KeyValuePair<OrderType, string>(OrderType.Limit, "canclimitelled"),`

I would commit a change, but can't get to it until this weekend. Just letting you know.

**Comment by ridicoulous** [comment]
Thank you for your feedback. This functionality is not tested by me yet

**Comment by dimsumcode** [comment]
I pushed fixes to my fork here, in case you are interested: https://github.com/dimsumcode/LiquidQuoine.Net/commits/master

**Comment by ridicoulous** [comment]
#18 thank you for contributing
