### ISSUE TITLE
OrderType enum , should we have a Stop?

### ISSUE THREAD

**Issue by dimsumcode** [ridicoulous/LiquidQuoine.Net#17]
When calling GetOrders() , Liquid sometimes returns orders of type "stop" (if the user set a stop order on the exchange itself).  The JsonConverter crashes because there is no OrderType.Stop defined.  Should we add a Stop OrderType? Or, better yet, there may be a way to configure the JsonConverter to handle undefined order types in the returned response. Haven't had time to research yet.

**Comment by ridicoulous** [comment]
The simplest way is to add order type in enum. I’ll do it at Monday

**Comment by ridicoulous** [comment]
#18
