### ISSUE TITLE
LiquidQuoineOrderTrade crashes on deserialization of date values

### ISSUE THREAD

**Issue by dimsumcode** [ridicoulous/LiquidQuoine.Net#19]
In class LiquidQuoineOrderTrade, the base class JsonConverter used for the "created_at" and "updated_at" properties is failing on deserialization because the json data being returned by API is in ISO format (for example "2019-03-29T21:12:48Z"), not unix epoch time.

I pushed the fix to my repo if you want to use it:

https://github.com/dimsumcode/LiquidQuoine.Net/commit/3ba0b8e6699b1bad10d76783e38552b626803ec0

**Comment by dimsumcode** [comment]
BTW, THANK you for creating this library!

**Comment by ridicoulous** [comment]
https://developers.quoine.com/v2#get-an-order
Looks like they made updates at backend but not at docs =)

**Comment by dimsumcode** [comment]
Yeah you're right. Their docs show unix epoch time.  Their API still returns epoch time for "Get Orders", but not for "Get Order Trades", which is ISO 8601 format. Just hoping they don't suddenly change it without letting us know!

**Comment by ridicoulous** [comment]
#20

**Comment by ridicoulous** [comment]
Just updated nuget package.
