### ISSUE TITLE
Create custom JSON converter to handle the different types of date formats, then update LiquidQuoineOrderTrade

### ISSUE THREAD

**Issue by dimsumcode** [ridicoulous/LiquidQuoine.Net#22]
Liquid API is inconsistent in returning date formats for Trade objects.  When calling GetOrderTrades(), it returns ISO string date formats. However, when calling "CloseTrade", the returned object uses Unix Epoch numeric date values. Therefore, we create a custom Json Converter to handle this behavior.

Link to commit 1/2:
https://github.com/dimsumcode/LiquidQuoine.Net/commit/8bc4f71c7ae05e675bf03cf85f05d0e60eae65fd

Link to commit 2/2:
https://github.com/dimsumcode/LiquidQuoine.Net/commit/bda55da314ed7f7c2d9834f4c0ffa51e1f64153f

**Comment by ridicoulous** [comment]
#25
