### ISSUE TITLE
Add TrailingStop OrderType

### ISSUE THREAD

**Issue by dimsumcode** [ridicoulous/LiquidQuoine.Net#27]
I committed updates to my repo here if you would like to use them:  https://github.com/dimsumcode/LiquidQuoine.Net/commit/32348dbabf0eeb4bac00a9fb23b7a0b4de3a1a7e

Added support for "trailing_stop" order types that were being returned by API.

**Comment by ridicoulous** [comment]
#28 thanks for contributing
