### ISSUE TITLE
websocket host to tap.liquid.com

### ISSUE THREAD

**Issue by kiranmaya** [ridicoulous/LiquidQuoine.Net#36]
/* javascript */

/////////////////////////////////////////////
// using Liquid Tap with Pusher library
var pusherKey = 'LIQUID'
var pusherChannel = 'price_ladders_cash_btcusd_sell'
var pusherEvent = 'updated'
var pusherTapHost = 'tap.liquid.com'

const tapSocket = new Pusher(pusherKey, {
  wsHost: pusherTapHost
});

var channel = tapSocket.subscribe(pusherChannel);
channel.bind(pusherEvent, function (data, metadata) {
  console.log("message from Liquid Tap: " + data);
});

/////////////////////////////////////////////
tried to change host,but not working.
tap.liquid.com websockets will make rest api obsolete .and low latency

**Comment by kiranmaya** [comment]
old pusher hosting works fine.

**Comment by ridicoulous** [comment]
Hello. Where did you find this hostname? I assume that it realized native websocket protocol instead pusher (Pusher is third party socket messaging provider) at this host.

**Comment by kiranmaya** [comment]
its here
https://developers.liquid.com/#authenticated
im getting connection refused,tried once.
-request
 add authentication for pusher.

**Comment by kiranmaya** [comment]
in api documentation,its said we can use pusher lib with tap.liquid, they also use pusher as server too.not any inhouse websocket server.

**Comment by ridicoulous** [comment]
I'll take look to it later. It should be some changes at pusher connecting

**Comment by kiranmaya** [comment]
websockets not working any more, geting "over qutoa" error .
