### ISSUE TITLE
PlaceMarginOrderAsync execution error

### ISSUE THREAD

**Issue by hayanobiton** [ridicoulous/LiquidQuoine.Net#42]
Executing PlaceMarginOrderAsync with OrderDirection option results in an error

await ApiClinet.PlaceMarginOrderAsync(BtcJpyID, OrderSide.Buy, OrderType.Limit, LeverageLevel.Level4, "JPY", (decimal)0.001, 1000000, null, OrderDirection.Netout);
⇒
  "order_direction": [ "not_valid" ]

I think that OrderDirection will not be converted by OrderDirectionConverter, but it is a post process with enumerated values

**Comment by hayanobiton** [comment]
I corrected it as follows

LiquidQuoinClinets.cs
parameters.AddOptionalParameter("order_direction", orderDirection);
↓
parameters.AddOptionalParameter("order_direction", JsonConvert.SerializeObject(orderDirection, new OrderDirectionConverter()));

OrderDirectionConverter.cs
            new KeyValuePair<OrderDirection, string>(OrderDirection.OneDirection, "one_direction"),
            new KeyValuePair<OrderDirection, string>(OrderDirection.OneDirection, "two_direction"),
            new KeyValuePair<OrderDirection, string>(OrderDirection.OneDirection, "netout")
↓
            new KeyValuePair<OrderDirection, string>(OrderDirection.OneDirection, "one_direction"),
            new KeyValuePair<OrderDirection, string>(OrderDirection.TwoDirection, "two_direction"),
            new KeyValuePair<OrderDirection, string>(OrderDirection.Netout, "netout")

**Comment by ridicoulous** [comment]
fixed in new version
