### ISSUE TITLE
Method not found exception in the constructor

### ISSUE THREAD

**Issue by NeuralDip** [ridicoulous/LiquidQuoine.Net#72]
Hello,
while constructing the client,
`using (var client = new LiquidQuoineClient())`
 i get the exception :

Method not found: 'Void CryptoExchange.Net.RestClient..ctor(CryptoExchange.Net.Objects.RestClientOptions, CryptoExchange.Net.Authentication.AuthenticationProvider)'.   at LiquidQuoine.Net.LiquidQuoineClient..ctor(LiquidQuoineClientOptions options)
   at LiquidQuoine.Net.LiquidQuoineClient..ctor()

i just installed the latest NuGet version in VisualStudio 2019

can you please give advise?

**Comment by ridicoulous** [comment]
Hello. You can try with newest version

**Comment by NeuralDip** [comment]
Unfortunately this is using standard2.1 and for compatibility reasons my project cannot support it.
thanks anyway
