### ISSUE TITLE
Other method not found

### ISSUE THREAD

**Issue by EricGarnier** [ridicoulous/LiquidQuoine.Net#75]
I try to use the nugget, and got:
System.MissingMethodException: Method not found: 'Void CryptoExchange.Net.Logging.Log.set_Level(CryptoExchange.Net.Logging.LogVerbosity)'.
   at LiquidQuoine.Net.LiquidQuoineClient..ctor(LiquidQuoineClientOptions options)

Any idea?
Du to others packages, I use  CryptoExchange.Net 4.2.8

Can it be this?

Thanks.
Eric

**Comment by ridicoulous** [comment]
Hello. Yes, current version depends on old version of CryptoExchange, pull requests are welcome, currently I'm a little busy

**Comment by ridicoulous** [comment]
It should be fixed via #77. Feel free to reopen if any issue
