### ISSUE TITLE
Websocket login problem

### ISSUE THREAD

**Issue by projeham** [ridicoulous/LiquidQuoine.Net#76]
Dear Sir,
I have a problem. When I use these codes:
`api = new LiquidQuoineClient(new LiquidQuoineClientOptions() { ApiCredentials = credentials });`
` ws = new LiquidQuoineSocketClient(new LiquidQuoineSocketClientOptions() { ApiCredentials = credentials });`
api variable is login correctly but ws variable is not login and authprovider property in ws is null.
Could you help me?

**Comment by ridicoulous** [comment]
Hello

I'll try take a look soon, I'm a little busy now. Also pull requests are welcome)
